//Quotes
const gamingQuotes = ["What is better? To be born good or to overcome your evil nature through great effort? -Paarthurnax, The Elder Scrolls 5: Skyrim", "The right man in the wrong place can make all the difference in the world. - G-Man, Half-Life 2",
"Stand in the ashes of a trillion dead souls, and ask the ghosts if honor matters. The silence is your answer. -Javik, Mass Effect 3", "Bring me a bucket, and I'll show you a bucket! -Psycho, Borderlands 2",
"Even in dark times, we cannot relinquish the things that make us human. -Khan, Metro 2033", "The healthy human mind doesn’t wake up in the morning thinking this is its last day on Earth. But I think that’s a luxury, not a curse. To know you’re close to the end is a kind of freedom. Good time to take inventory. Out-gunned. Outnumbered. Out of our minds. On a suicide mission. But the sand and the rocks here, stained with thousands of years of warfare. They will remember us. For this. Because out of all our vast array of nightmares, this is the one we choose for ourselves. We go forward like a breath exhaled from the Earth. With vigor in our hearts and one goal in sight: We. Will. Kill him. -Captain Price, Call of Duty: Modern Warfare 2",
"It's a funny thing, ambition. It can take one to sublime heights or harrowing depths. And sometimes they are one and the same. -Emily Kaldwin, Dishonored", "No gods or kings. Only man. -Andrew Ryan, BioShock", "It's time to kick ass and chew bubblegum... and I'm all outta gum. -Duke Nukem, Duke Nukem 3D",
"Life is cruel. Of this I have no doubt. One can only hope that one leaves behind a lasting legacy. But so often, the legacies we leave behind... are not the ones we intended. -Queen Myrrah, Gears of War 2", "It's easy to forget what a sin is in the middle of a battlefield. -Solid Snake, Metal Gear Solid",
"Who are you, that do not know your history? -Ulysses, Fallout New Vegas", "Nothing is true, everything is permitted. -Ezio Auditore, Assassin’s Creed 2", "War. War never changes. -Narrator, Fallout 3", "What is a man? A miserable little pile of secrets. -Dracula, Castlevania: Symphony of the Night", 
"A man chooses; a slave obeys. -Andrew Ryan, BioShock", "Wake me when you need me. -John-117, Halo 3", "I used to be an adventurer like you, until I took an arrow to the knee. -Town Guard, Elder Scrolls 5: Skyrim", "Science isn't about why! It’s about why not! -Cave Johnson, Portal 2", 
"Hard to see big picture behind pile of corpses. -Mordin Solus, Mass Effect 3", "Does this unit have a soul? -Legion, Mass Effect 3", "It's more important to master the cards you're holding than to complain about the ones your opponents were dealt. -Grimsley, Pokemon Black and White", "War is where the young and stupid are tricked by the old and bitter into killing each other. -Niko Bellic, GTA 4",
"When life gives you lemons, don't make lemonade. Make life take the lemons back! Get mad! I don't want your damn lemons! What am I supposed to do with these?! Demand to see life's manager! Make life rue the day it thought it could give Cave Johnson lemons! Do you know who I am?! I'm the man who's gonna burn your house down! With the lemons! I'm gonna get my engineers to invent a combustible lemon that burns your house down! -Cave Johnson, Portal 2",
"Send me out...with a bang. -Sgt. Avery Johnson, Halo 3", "Force answers force, war breeds war, and death only brings death. To break this vicious circle, one must do more than just act without any thought or doubt. -Metro 2033", "DEATH IS A PREFERABLE ALTERNATIVE TO COMMUNISM. -Fallout 3",
"The cake is a lie. -Portal", "Wisdom is the offspring of Suffering and Time. -Emperor Izaro, Path of Exile", "It is a sign of strength, to cry out against fate, rather than to bow one's head and succumb. -Gabriel Angelos, Warhammer 40,000: Dawn of War II", "Too many people have opinions on things they know nothing about. And the more ignorant they are, the more opinions they have. -Thomas Hildern, Fallout: New Vegas",
"Ideals Are Strengthen By The Challenges They Endure. -Fallout: New Vegas", "I survived because the fire inside burnt hotter than the fire around me. -Joshua Graham Fallout: New Vegas", "We Impose Order On The Chaos Of Organic Evolution. You Exist Because We Allow It. And You Will End Because We Demand It. -Sovereign Mass Effect",
"Did I Ever Tell You The Definition Of Insanity? -Vaas, Far Cry 3"];

const motivationalQuotes = ["There is nothing impossible to they who will try. -Alexander the Great", "The bad news is time flies. The good news is you're the pilot. -Michael Altshuler", "You make a choice: continue living your life feeling muddled in this abyss of self-misunderstanding, or you find your identity independent of it. You draw your own box. -Duchess Meghan", "A ship in harbor is safe, but that is not what ships are built for. -John A. Shedd", "No man chooses evil because it is evil; he only mistakes it for happiness, the good he seeks. -Mary Wollstonecraft",
"Go where you are appreciated, not tolerated -Unknown", "If I have an apple and you have an apple and we exchange them, we both still have one apple. However, if I have an idea and you also have an idea and we exchange them, we both have two ideas. -Unknown", "If you are good you'll tell everyone. If you are great people will tell you -Unknown", "There is nothing noble about being better than your fellow man. Only being better than your former self. -Earnest Hemingway", "A year from now, you'll wish you would have started today.", "Maturity begins when you can be wrong, and not feel as though you have lost.", 
"You either suffer the pain of discipline or you suffer the pain of regret.", "We have a tendency to want the other person to be a finished product while we give ourselves the grace to evolve.", "You could be the ripest, juiciest peach in the world, and there will always be someone who hates peaches.", "What hurts me the most, is knowing that there are people who keep saying they want to die when all they really want is to start living.", "In order to get something you never had, you have to do something you never have done",
"Man can endure any 'how', as long as he has a 'why'.", "If there is no solution to the problem then don't waste time worrying about it. If there is a solution to the problem then don't waste time worrying about it.” - The Dalai Lama", "Don't practice til you get it right, practice til you can't get it wrong.", "A smooth sea never made a skilled sailor.", "We judge others by their actions, but we judge ourselves by our intentions.",
"Give a man a mask and he will show you his true self. - Oscar Wilde", "If you're lonely when you're alone, you're in bad company", "Don't set yourself on fire to keep others warm", "If you want to know the measure of a man then watch how he treats his inferiors, not his equals", "When a person tells you that you hurt them, you don't get to decide that you didn't.", "Don't pray for an easier life, pray to be a stronger person", "Isn't it funny how day by day nothing changes but when we look back everything is different... -C.S Lewis",
"Most men lead lives of quiet desperation and go to the grave with the song still in them.", "Sucking at something is the first step to being kinda good at it", "The master has probably failed more times the beginner has even tried.", "If you're the smartest person in the room, you're probably in the wrong room.", "Holding onto anger is like drinking poison and expecting the other person to die. - Buddha", "An army of donkeys led by a lion will always defeat an army of lions led by a donkey. -Mongolian proverb", "Wise men talk because they have something to say. Fools talk because they have to say something. - Plato",
"Make friends with pain, and you've got a friend for life.", "If the problem can be solved why worry? If the problem cannot be solved worrying will do you no good.", "You miss 100% of the shots you don't take. -Wayne Gretzky", "Stupidity has a price.", "Never interrupt your enemy when he is making a mistake", "Be self reliant, Live your life like there's no one looking out for you", "No one's coming to save you, you have to save yourself", "The best portion of a good man’s life is his little, nameless, unremembered acts of kindness and of love.", "At the end of the game, the King and the Pawn go back into the same box",
"It is possible to commit no mistakes and still lose. That is not a weakness; that is life. -Captain Picard", "He who angers you controls you", "We’re all stories in the end. Just make it a good one.", "Fortune favors the bold.", "Every man is the Artisan of his own fortune", "Do not let good be the enemy of great", "Only a fool argues with a fool", "Nobody has ever looked back on their life wishing they had spent more time at work", "Live well. It is the greatest revenge", "Show me your friends, and I'll show you you're future",
"Live your life like someone else is watching you", "Don’t take criticism from someone you wouldn’t take advice from.", "What’s easy & what’s right are rarely the same thing.", "If you’re going through hell, keep going. -Winston Churchill", "It is during our darkest moments that we must focus to see the light. -Aristotle", "Forgive yourself for your faults and your mistakes and move on. -Les Brown", "Accept responsibility for your life. Know that it is you who will get you where you want to go, no one else. -Les Brown", "If you live off a man’s compliments, you’ll die from his criticism.", "The world didn't get worse, your eyes just got wider.", 
"If you put someone on a pedestal, they have no choice but to look down on you."];

//Gets Random Quote from Gaming quotes Array
function randGameQuote() {
    let quote = gamingQuotes[Math.floor(Math.random() * gamingQuotes.length)]
    document.getElementById('quote').textContent = quote;
}
//Applies function to Gaming Quote Button
document.getElementById('gaming-quote').addEventListener('click', ()=>{
    randGameQuote();
})

//Gets Random Quote from Motivational Quotes Array 
function randMotivationalQuote() {
    let quote = motivationalQuotes[Math.floor(Math.random() * motivationalQuotes.length)];
    document.getElementById('quote').textContent = quote;
}
document.addEventListener('click', ()=>{
    randMotivationalQuote();
});