//Quotes
const gamingQuotes = ["We all make choices, but in the end... our choices make us. -Andrew Ryan","What is better? To be born good or to overcome your evil nature through great effort? -Paarthurnax, The Elder Scrolls 5: Skyrim", "The right man in the wrong place can make all the difference in the world. - G-Man, Half-Life 2",
"Stand in the ashes of a trillion dead souls, and ask the ghosts if honor matters. The silence is your answer. -Javik, Mass Effect 3", "Bring me a bucket, and I'll show you a bucket! -Psycho, Borderlands 2",
"Even in dark times, we cannot relinquish the things that make us human. -Khan, Metro 2033", "The healthy human mind doesn’t wake up in the morning thinking this is its last day on Earth. But I think that’s a luxury, not a curse. To know you’re close to the end is a kind of freedom. Good time to take inventory. Out-gunned. Outnumbered. Out of our minds. On a suicide mission. But the sand and the rocks here, stained with thousands of years of warfare. They will remember us. For this. Because out of all our vast array of nightmares, this is the one we choose for ourselves. We go forward like a breath exhaled from the Earth. With vigor in our hearts and one goal in sight: We. Will. Kill him. -Captain Price, Call of Duty: Modern Warfare 2",
"It's a funny thing, ambition. It can take one to sublime heights or harrowing depths. And sometimes they are one and the same. -Emily Kaldwin, Dishonored", "No gods or kings. Only man. -Andrew Ryan, BioShock", "It's time to kick ass and chew bubblegum... and I'm all outta gum. -Duke Nukem, Duke Nukem 3D",
"Life is cruel. Of this I have no doubt. One can only hope that one leaves behind a lasting legacy. But so often, the legacies we leave behind... are not the ones we intended. -Queen Myrrah, Gears of War 2", "It's easy to forget what a sin is in the middle of a battlefield. -Solid Snake, Metal Gear Solid",
"Who are you, that do not know your history? -Ulysses, Fallout New Vegas", "Nothing is true, everything is permitted. -Ezio Auditore, Assassin’s Creed 2", "War. War never changes. -Narrator, Fallout 3", "What is a man? A miserable little pile of secrets. -Dracula, Castlevania: Symphony of the Night", 
"A man chooses; a slave obeys. -Andrew Ryan, BioShock", "Wake me when you need me. -John-117, Halo 3", "I used to be an adventurer like you, until I took an arrow to the knee. -Town Guard, Elder Scrolls 5: Skyrim", "Science isn't about why! It’s about why not! -Cave Johnson, Portal 2", 
"Hard to see big picture behind pile of corpses. -Mordin Solus, Mass Effect 3", "Does this unit have a soul? -Legion, Mass Effect 3", "It's more important to master the cards you're holding than to complain about the ones your opponents were dealt. -Grimsley, Pokemon Black and White", "War is where the young and stupid are tricked by the old and bitter into killing each other. -Niko Bellic, GTA 4",
"When life gives you lemons, don't make lemonade. Make life take the lemons back! Get mad! I don't want your damn lemons! What am I supposed to do with these?! Demand to see life's manager! Make life rue the day it thought it could give Cave Johnson lemons! Do you know who I am?! I'm the man who's gonna burn your house down! With the lemons! I'm gonna get my engineers to invent a combustible lemon that burns your house down! -Cave Johnson, Portal 2",
"Send me out...with a bang. -Sgt. Avery Johnson, Halo 3", "Force answers force, war breeds war, and death only brings death. To break this vicious circle, one must do more than just act without any thought or doubt. -Metro 2033", "DEATH IS A PREFERABLE ALTERNATIVE TO COMMUNISM. -Fallout 3",
"The cake is a lie. -Portal", "Wisdom is the offspring of Suffering and Time. -Emperor Izaro, Path of Exile", "It is a sign of strength, to cry out against fate, rather than to bow one's head and succumb. -Gabriel Angelos, Warhammer 40,000: Dawn of War II", "Too many people have opinions on things they know nothing about. And the more ignorant they are, the more opinions they have. -Thomas Hildern, Fallout: New Vegas",
"Ideals Are Strengthen By The Challenges They Endure. -Fallout: New Vegas", "I survived because the fire inside burnt hotter than the fire around me. -Joshua Graham Fallout: New Vegas", "We Impose Order On The Chaos Of Organic Evolution. You Exist Because We Allow It. And You Will End Because We Demand It. -Sovereign Mass Effect",
"Did I Ever Tell You The Definition Of Insanity? -Vaas, Far Cry 3", "A hero need not speak. When he is gone, the world will speak for him. -Halo 3"];

const motivationalQuotes = ["There is nothing impossible to they who will try. -Alexander the Great", "The bad news is time flies. The good news is you're the pilot. -Michael Altshuler", "You make a choice: continue living your life feeling muddled in this abyss of self-misunderstanding, or you find your identity independent of it. You draw your own box. -Duchess Meghan", "A ship in harbor is safe, but that is not what ships are built for. -John A. Shedd", "No man chooses evil because it is evil; he only mistakes it for happiness, the good he seeks. -Mary Wollstonecraft",
"Go where you are appreciated, not tolerated -Unknown", "If I have an apple and you have an apple and we exchange them, we both still have one apple. However, if I have an idea and you also have an idea and we exchange them, we both have two ideas. -Unknown", "If you are good you'll tell everyone. If you are great people will tell you -Unknown", "There is nothing noble about being better than your fellow man. Only being better than your former self. -Earnest Hemingway", "A year from now, you'll wish you would have started today.", "Maturity begins when you can be wrong, and not feel as though you have lost.", 
"You either suffer the pain of discipline or you suffer the pain of regret.", "We have a tendency to want the other person to be a finished product while we give ourselves the grace to evolve.", "You could be the ripest, juiciest peach in the world, and there will always be someone who hates peaches.", "What hurts me the most, is knowing that there are people who keep saying they want to die when all they really want is to start living.", "In order to get something you never had, you have to do something you never have done",
"Man can endure any 'how', as long as he has a 'why'.", "If there is no solution to the problem then don't waste time worrying about it. If there is a solution to the problem then don't waste time worrying about it.” - The Dalai Lama", "Don't practice til you get it right, practice til you can't get it wrong.", "A smooth sea never made a skilled sailor.", "We judge others by their actions, but we judge ourselves by our intentions.",
"Give a man a mask and he will show you his true self. - Oscar Wilde", "If you're lonely when you're alone, you're in bad company", "Don't set yourself on fire to keep others warm", "If you want to know the measure of a man then watch how he treats his inferiors, not his equals", "When a person tells you that you hurt them, you don't get to decide that you didn't.", "Don't pray for an easier life, pray to be a stronger person", "Isn't it funny how day by day nothing changes but when we look back everything is different... -C.S Lewis",
"Most men lead lives of quiet desperation and go to the grave with the song still in them.", "Sucking at something is the first step to being kinda good at it", "The master has probably failed more times the beginner has even tried.", "If you're the smartest person in the room, you're probably in the wrong room.", "Holding onto anger is like drinking poison and expecting the other person to die. - Buddha", "An army of donkeys led by a lion will always defeat an army of lions led by a donkey. -Mongolian proverb", "Wise men talk because they have something to say. Fools talk because they have to say something. - Plato",
"Make friends with pain, and you've got a friend for life.", "If the problem can be solved why worry? If the problem cannot be solved worrying will do you no good.", "You miss 100% of the shots you don't take. -Wayne Gretzky", "Stupidity has a price.", "Never interrupt your enemy when he is making a mistake", "Be self reliant, Live your life like there's no one looking out for you", "No one's coming to save you, you have to save yourself", "The best portion of a good man’s life is his little, nameless, unremembered acts of kindness and of love.", "At the end of the game, the King and the Pawn go back into the same box",
"It is possible to commit no mistakes and still lose. That is not a weakness; that is life. -Captain Picard", "He who angers you controls you", "We’re all stories in the end. Just make it a good one.", "Fortune favors the bold.", "Every man is the Artisan of his own fortune", "Do not let good be the enemy of great", "Only a fool argues with a fool", "Nobody has ever looked back on their life wishing they had spent more time at work", "Live well. It is the greatest revenge", "Show me your friends, and I'll show you you're future",
"Live your life like someone else is watching you", "Don’t take criticism from someone you wouldn’t take advice from.", "What’s easy & what’s right are rarely the same thing.", "If you’re going through hell, keep going. -Winston Churchill", "It is during our darkest moments that we must focus to see the light. -Aristotle", "Forgive yourself for your faults and your mistakes and move on. -Les Brown", "Accept responsibility for your life. Know that it is you who will get you where you want to go, no one else. -Les Brown", "If you live off a man’s compliments, you’ll die from his criticism.", "The world didn't get worse, your eyes just got wider.", 
"If you put someone on a pedestal, they have no choice but to look down on you."];

const officeQuotes = ["Sometimes I’ll start a sentence and I don’t even know where it’s going. I just hope I find it along the way. -Michael Scott (Season 5, The Duel)", "I’m not superstitious, but I am a little stitious. -Michael Scott (Season 4, Fun Run)", "I wish there was a way to know you’re in the good old days, before you’ve actually left them -Andy Bernard (Season 9, Finale)", "The worst thing about prison was the dementors. -Michael “Prison Mike” Scott (Season 3, The Convict)", 
"Abraham Lincoln once said that 'If you're a racist, I will attack you with the North, and these are the principles I carry with me in the workplace. -Michael Scott (Season 1, Diversity Day)", "I feel God in this Chili’s tonight. -Pam Beesly (Season 2, The Dundies)", "In the end, the greatest snowball isn't a snowball at all. It's fear. Merry Christmas. -Dwight Schrute (Season 7, Classy Christmas)", "Did I stutter? -Stanley Hudson (Season 4, Did I Stutter)", "Guess what, I have flaws. What are they? Oh, I don't know. I sing in the shower. Sometimes I spend too much time volunteering. Occasionally I'll hit somebody with my car. So sue me. -Michael Scott (Season 4, Fun Run)",
"It's like I used to tell my wife. I do not apologize unless I think I'm wrong. And if you don't like it you can leave. And I say the same thing to my current wife and I'll say it to my next one, too. -Stanley Hudson (Season 4, Did I Stutter)", "I feel like all my kids grew up, and then they married each other. It’s every parent’s dream. -Michael Scott (Season 9, Finale)", "I am fast. To give you a reference point. I'm somewhere between a snake and a mongoose. And a panther. -Dwight Schrute (Season 3, The Merger)", "Oh my God it's happening! Everybody stay calm. Stay f*cking calm! -Michael Scott (Season 5, Stress Relief: Part. 1)", 
"Whenever I'm about to do something, I think, 'Would an idiot do that?' And if they would, I do not do that thing. -Dwight Schrute (Season 3, Business School)", "Bros before hos. Why? Because your bros are always there for you. They have got your back after your ho rips out your heart for no good reason. And you are nothing but great to your ho, and you told her that she was the only ho for you, and that she was better than all the other hos in the world. And then, suddenly, she's not your ho no mo. -Michael Scott (Season 3, A Benihana Christmas)", 
"There's something about an underdog that really inspires the unexceptional. -Robert California (Season 8, The Incentive)", "People underestimate the power of nostalgia. Nostalgia is truly one of the greatest human weaknesses, second only to the neck. -Dwight Schrute (Season 9, The Farm)", "Why are you the way that you are? - Michael Scott (Season 2, Casino Night)", "Sorry I annoyed you with my friendship. -Andy Bernard (Season 3, The Return)", "Fact: Bears eat beets. Bears. Beets. Battlestar Galactica. -Jim Halpert (Season 3, Product Recall)",
"In the wild, there is no healthcare. In the wild healthcare is, 'Ow, I hurt my leg. I can't run. A lion eats me, and I'm dead.' Well, I'm not dead. I'm the lion. You're dead. -Dwight Schrute (Season 1, Health Care)", "Meredith, you lit your hair on fire today. What about tomorrow? What is going to happen when you come into work and you're dead? -Michael Scott (Season 5, Moroccan Christmas)", "Nobody should have to go to work thinking, 'Oh this is the place that I might die today.' That's what a hospital is for. An office is for not dying. An office is a place to live life to the fullest. To the max. An office is a place where dreams come true. -Michael Scott (Season 5, Stress Relief: Part 1)",
"If I had a gun with two bullets and I was in a room with Hitler, Bin Laden and Toby, I would shoot Toby twice. -Michael Scott (Season 6, The Chump)", "Dwight, you ignorant slut! -Michael Scott (Season 3, Safety Training)", "My, philosophy is, basically this. And this is something that I live by. And I always have. And I always will. Don't, ever, for any reason, do anything, to anyone, for any reason, ever, no matter what, no matter where, or who you are with, or, or where you are going, or, or where you've been. Ever. For any reason. Whatsoever. -Michael Scott (Season 5, The Duel)", "Would I rather be feared or loved? Easy. Both. I want people to be afraid of how much they love me. -Michael Scott", 
"Identity theft is not a joke, Jim! Millions of families suffer every year. -Dwight Schrute", "Life is short. Drive fast and leave a sexy corpse. That’s one of my mottos. -Stanley Hudson", "No, Rose, they are not breathing. And they have no arms or legs… Where are they? You know what? If we come across somebody with no arms or legs, do we bother resuscitating them? I mean, what quality of life do we have there? -Michael Scott", "Fool me once, strike one. Fool me twice, strike three. -Michael Scott", "The people here are amazing debaters. I guess you can say they are master-baters. -Kevin Malone", "I want you to rub butter on my foot… Pam, please? I have Country Crock. -Michael Scott", "I love inside jokes. I’d love to be a part of one someday. -Michael Scott", 
"I’ve got a golden ticket idea. Why don’t you skip on up to the roof and jump off? -Stanley Hudson", "It’s a real shame because studies have shown that more information gets passed through water cooler gossip than through official memos. Which puts me at a disadvantage because I bring my own water to work. -Dwight Schrute", "I think it’s great that the company’s making a commercial, because not very many people have heard of us. I mean, when I tell people I work at Dunder Mifflin, they think that we sell mufflers or muffins or mittens or… and frankly, all of those sound better than paper, so I let it slide. -Jim Halpert", 
"Boy, have you done lost your mind? Cause I’ll help you find it! -Stanley Hudson", "Ain’t no party like a Scranton party cause a Scranton party don’t stop! -Michael Scott", "I’m not offended by homosexuality. In the ’60s I made love to many, many women, often outdoors, in the mud and the rain… and it’s possible a man slipped in. (Shrugs) There’d be no way of knowing. -Creed Bratton", "One day Michael came in and complained about a speed bump on the highway. I wonder who he ran over then. -Jim Halpert",];

//Gets Random Quote from Gaming quotes Array
function randGameQuote() {
    let quote = gamingQuotes[Math.floor(Math.random() * gamingQuotes.length)]
    document.getElementById('quote').textContent = quote;
}
//Applies function to Gaming Quote Button
document.getElementById('gaming-quote').addEventListener('click', ()=>{
    randGameQuote();
})

//Gets Random Quote from Motivational Quotes Array 
function randMotivationalQuote() {
    let quote = motivationalQuotes[Math.floor(Math.random() * motivationalQuotes.length)];
    document.getElementById('quote').textContent = quote;
}
//Applies function to Motivational Quote Button
document.getElementById('motivational-quote').addEventListener('click', ()=>{
    randMotivationalQuote();
});

//Gets Random Quote from the Office quotes Array
function getOfficeQuote(){
    let quote = officeQuotes[Math.floor(Math.random() * officeQuotes.length)];
    document.getElementById('quote').textContent = quote;
}
//Applies function to Office quote button
document.getElementById('office-quote').addEventListener('click', ()=>{
    getOfficeQuote()
})