//Quotes
const gamingQuotes = ["What is better? To be born good or to overcome your evil nature through great effort? -Paarthurnax, The Elder Scrolls 5: Skyrim", "The right man in the wrong place can make all the difference in the world. - G-Man, Half-Life 2",
"Stand in the ashes of a trillion dead souls, and ask the ghosts if honor matters. The silence is your answer. -Javik, Mass Effect 3", "Bring me a bucket, and I'll show you a bucket! -Psycho, Borderlands 2",
"Even in dark times, we cannot relinquish the things that make us human. -Khan, Metro 2033", "The healthy human mind doesn’t wake up in the morning thinking this is its last day on Earth. But I think that’s a luxury, not a curse. To know you’re close to the end is a kind of freedom. Good time to take inventory. Out-gunned. Outnumbered. Out of our minds. On a suicide mission. But the sand and the rocks here, stained with thousands of years of warfare. They will remember us. For this. Because out of all our vast array of nightmares, this is the one we choose for ourselves. We go forward like a breath exhaled from the Earth. With vigor in our hearts and one goal in sight: We. Will. Kill him. -Captain Price, Call of Duty: Modern Warfare 2",
"It's a funny thing, ambition. It can take one to sublime heights or harrowing depths. And sometimes they are one and the same. -Emily Kaldwin, Dishonored", "No gods or kings. Only man. -Andrew Ryan, BioShock", "It's time to kick ass and chew bubblegum... and I'm all outta gum. -Duke Nukem, Duke Nukem 3D",
"Life is cruel. Of this I have no doubt. One can only hope that one leaves behind a lasting legacy. But so often, the legacies we leave behind... are not the ones we intended. -Queen Myrrah, Gears of War 2", "It's easy to forget what a sin is in the middle of a battlefield. -Solid Snake, Metal Gear Solid",
"Who are you, that do not know your history? -Ulysses, Fallout New Vegas", "Nothing is true, everything is permitted. -Ezio Auditore, Assassin’s Creed 2", "War. War never changes. -Narrator, Fallout 3", "What is a man? A miserable little pile of secrets. -Dracula, Castlevania: Symphony of the Night", 
"A man chooses; a slave obeys. -Andrew Ryan, BioShock", "Wake me when you need me. -John-117, Halo 3", "I used to be an adventurer like you, until I took an arrow to the knee. -Town Guard, Elder Scrolls 5: Skyrim", "Science isn't about why! It’s about why not! -Cave Johnson, Portal 2", 
"Hard to see big picture behind pile of corpses. -Mordin Solus, Mass Effect 3", "Does this unit have a soul? -Legion, Mass Effect 3", "It's more important to master the cards you're holding than to complain about the ones your opponents were dealt. -Grimsley, Pokemon Black and White", "War is where the young and stupid are tricked by the old and bitter into killing each other. -Niko Bellic, GTA 4",
"When life gives you lemons, don't make lemonade. Make life take the lemons back! Get mad! I don't want your damn lemons! What am I supposed to do with these?! Demand to see life's manager! Make life rue the day it thought it could give Cave Johnson lemons! Do you know who I am?! I'm the man who's gonna burn your house down! With the lemons! I'm gonna get my engineers to invent a combustible lemon that burns your house down! -Cave Johnson, Portal 2",
"Send me out...with a bang. -Sgt. Avery Johnson, Halo 3", "Force answers force, war breeds war, and death only brings death. To break this vicious circle, one must do more than just act without any thought or doubt. -Metro 2033", "DEATH IS A PREFERABLE ALTERNATIVE TO COMMUNISM. -Fallout 3",
"The cake is a lie. -Portal", "Wisdom is the offspring of Suffering and Time. -Emperor Izaro, Path of Exile", "It is a sign of strength, to cry out against fate, rather than to bow one's head and succumb. -Gabriel Angelos, Warhammer 40,000: Dawn of War II", "Too many people have opinions on things they know nothing about. And the more ignorant they are, the more opinions they have. -Thomas Hildern, Fallout: New Vegas",
"Ideals Are Strengthen By The Challenges They Endure. -Fallout: New Vegas", "I survived because the fire inside burnt hotter than the fire around me. -Joshua Graham Fallout: New Vegas", "We Impose Order On The Chaos Of Organic Evolution. You Exist Because We Allow It. And You Will End Because We Demand It. -Sovereign Mass Effect",
"Did I Ever Tell You The Definition Of Insanity? -Vaas, Far Cry 3"];

//Gets Random Quote from Array
function randGameQuote() {
    let quote = gamingQuotes[Math.floor(Math.random() * gamingQuotes.length)]
    document.getElementById('quote').textContent = quote;
}
//Applies function to Gaming Quote Button
document.getElementById('gaming-quote').addEventListener('click', ()=>{
    randGameQuote();
})